version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pcpartpicker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: pcpartpicker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pcpartpicker_network

volumes:
  mysql_data:

networks:
  pcpartpicker_network:
    driver: bridge
